groups:
  netsec:
    display_name: NetSec
    match:
      - "Secure Firewall Threat Defense"
      - "Firepower Threat Defense"
      - "Secure Firewall Management Center"
      - "Firepower Management Center"
      - "Firepower Extensible Operating System"
      - "FXOS"
      - "Adaptive Security Appliance"
      - "ASA"
      - "Secure Web Appliance"
      - "Secure Email"
      - "Secure Email and Web Manager"
      - "Secure Endpoint"
      - "Secure Endpoint Private Cloud Console"
      - "UTD SNORT IPS Engine"
      - "Secure Network Analytics"
      - "Cyber Vision"
      - "Duo"
      - "Duo Authentication Proxy"
    exclude: []

  enterprise:
    display_name: Enterprise Networking
    match:
      - "IOS XE"
      - "IOS XR"
      - "IOS"
      - "Digital Network Architecture Center"
      - "DNA Center"
      - "DNA Spaces"
      - "Identity Services Engine"
      - "ISE Passive Identity Connector"
      - "Prime Infrastructure"
      - "Evolved Programmable Network Manager"
      - "EPNM"
      - "Network Services Orchestrator"
      - "Small Business RV Series Router"
      - "Catalyst SD-WAN"
      - "SD-WAN Manager"
      - "SD-WAN vEdge"
      - "SD-WAN vContainer"
    exclude: []

  datacenter:
    display_name: Data Center
    match:
      - "NX-OS"
      - "Nexus Dashboard"
      - "Application Policy Infrastructure Controller"
      - "APIC"
      - "Data Center Network Manager"
      - "ACI Mode"
      - "Cloud Native Broadband Router"
      - "Enterprise NFV Infrastructure"
      - "ConfD"
    exclude: []

  compute:
    display_name: Compute
    match:
      - "Unified Computing System"
      - "UCS"
      - "Intersight Virtual Appliance"
    exclude: []

  wireless:
    display_name: Wireless
    match:
      - "Wireless LAN Controller"
      - "WLC"
      - "Aironet Access Point"
      - "Ultra-Reliable Wireless Backhaul"
    exclude: []

  collab:
    display_name: Collaboration
    match:
      - "Unified Communications Manager"
      - "IM and Presence"
      - "Unity Connection"
      - "Webex App"
      - "Webex Meetings"
      - "TelePresence"
      - "RoomOS"
      - "Meeting Management"
      - "Emergency Responder"
      - "BroadWorks"
      - "Session Initiation Protocol"
      - "SIP Software"
      - "Unified Contact Center"
      - "Packaged Contact Center Enterprise"
      - "Prime Collaboration Deployment"
      - "Finesse"
      - "Virtualized Voice Browser"
      - "Unified Intelligence Center"
      - "Intelligent Contact Management"
      - "SocialMiner"
      - "Enterprise Chat and Email"
    exclude: []

  cloud:
    display_name: Cloud
    match:
      - "Meraki"
      - "Smart License Utility"
      - "Smart PHY"
      - "Ultra Cloud Core"
      - "Ultra Gateway Platform"
      - "ThousandEyes"
    exclude: []
